### PR TITLE
Don't mess with timezone

### PR DESCRIPTION
**Pull request by bserdar**

### CODE REVIEW

**Comment by jewzaam** [comment]
How does this impact persistence of date?  We specifically didn't want to save timestamp with time zone [1].  I assume this is the one place conversion to UTC is happening.  Maybe if I knew what problem was being solved by this it would be clearer.  Is there an issue that should be linked?

[1] http://dev.docs.lightblue.io/key_decisions/README.html#how-will-we-represent-date-in-json

**Comment by bserdar** [comment]
The problem is the initial decision that we return GMT. Dates are stored as
dates, not strings, so nothing changes in terms of persistence. With this
change, date values are interpreted in the local time zone, not in GMT,
that's the only change.

So, when you save a date 2015/01/01 - 04:00:00 EDT and read it back, you'll
get 2015/01/01 - 04:00:00 EDT, not 2015/01/01-08:00:00 GMT.

**Comment by dcrissman** [comment]
Does this change have a sibling in the lightblue-client for ClientConstants? We also set the timezone to GMT there.

**Comment by bserdar** [comment]
No, I didn't realize that. I'll remove that one as well.

**Pull request merged**
